<?php

function getSupportedLanguages(): array {
    return [
        'en' => 'English',
        'zh' => '中文',
    ];
}

function getCurrentLanguage(): string {
    if (isset($_SESSION['language']) && array_key_exists($_SESSION['language'], getSupportedLanguages())) {
        return $_SESSION['language'];
    }
    return 'en';
}

function setCurrentLanguage(string $lang): void {
    $languages = getSupportedLanguages();
    if (!array_key_exists($lang, $languages)) {
        $lang = 'en';
    }
    $_SESSION['language'] = $lang;
}

function t(string $key): string {
    static $translations = [
        'en' => [
            'nav_admin' => 'Admin',
            'nav_seller' => 'Seller',
            'nav_cart' => 'Cart',
            'nav_dashboard' => 'Dashboard',
            'nav_profile' => 'Profile',
            'nav_logout' => 'Logout',
            'nav_login' => 'Login',
            'nav_register' => 'Register',
            'nav_cart_with_count' => 'Cart (%d)',
            'brand_name' => 'Shop',
            'theme_night' => 'Night',
            'theme_light' => 'Light',

            'dashboard_title' => 'My Dashboard',
            'dashboard_menu' => 'Menu',
            'dashboard_my_orders' => 'My Orders',
            'dashboard_profile_settings' => 'Profile & Settings',
            'dashboard_continue_shopping' => 'Continue Shopping',
            'dashboard_cart' => 'Cart',
            'dashboard_become_seller' => 'Become a Seller',

            'orders_table_order_id' => 'Order ID',
            'orders_table_total' => 'Total',
            'orders_table_status' => 'Status',
            'orders_table_date' => 'Date',
            'orders_table_action' => 'Action',
            'orders_view_details' => 'View Details',
            'orders_empty_message' => 'You have no orders yet.',
            'orders_start_shopping' => 'Start Shopping',

            'order_status_pending' => 'Pending',
            'order_status_processing' => 'Processing',
            'order_status_shipped' => 'Shipped',
            'order_status_delivered' => 'Delivered',
            'order_status_cancelled' => 'Cancelled',

            'language_select_title' => 'Choose Your Language',
            'language_select_intro' => 'Please select your preferred language.',
            'language_english' => 'English',
            'language_chinese' => 'Chinese',
            'language_save' => 'Save Language',
            'profile_language_label' => 'Language',

            'search_placeholder' => 'Search products...',
            'search_button' => 'Search',

            'category_all' => 'All',
            'category_electronics' => 'Electronics',
            'category_clothing' => 'Clothing',
            'category_home_kitchen' => 'Home & Kitchen',
            'category_books' => 'Books',
            'category_sports' => 'Sports',

            'product_stock_label' => 'Stock',
            'home_view_details' => 'View Details',
            'home_login_to_buy' => 'Login to Buy',
            'product_description_title' => 'Description',
            'product_available_from_sellers' => 'Available from Sellers:',
            'product_quantity_label' => 'Quantity:',
            'product_add_to_cart_button' => 'Add to Cart',
            'product_out_of_stock' => 'Out of Stock',
            'product_no_sellers_message' => 'No sellers available for this product.',

            'seller_dashboard_title' => 'Seller Dashboard',
            'seller_dashboard_welcome' => 'Welcome, %s. Here is an overview of your sales activity.',
            'seller_dashboard_total_products' => 'Total Products',
            'seller_dashboard_total_orders' => 'Total Orders',
            'seller_dashboard_gross_revenue' => 'Gross Revenue',
            'seller_dashboard_platform_fees' => 'Platform Fees (10%)',
            'seller_dashboard_net_revenue' => 'Net Revenue (after fees)',
            'seller_dashboard_actions' => 'Seller Actions',
            'seller_dashboard_my_products' => 'My Products',
            'seller_dashboard_my_orders' => 'My Orders',
            'seller_dashboard_back_to_store' => 'Back to Store',

            'seller_products_title' => 'My Products',
            'seller_products_intro' => 'Create and manage the products you sell.',
            'seller_products_add_new' => 'Add New Product',
            'seller_products_name' => 'Name',
            'seller_products_description' => 'Description',
            'seller_products_price' => 'Price',
            'seller_products_stock' => 'Stock',
            'seller_products_image' => 'Image',
            'seller_products_create_button' => 'Create Product',
            'seller_products_your_products' => 'Your Products',
            'seller_products_image_column' => 'Image',
            'seller_products_name_column' => 'Name',
            'seller_products_price_stock_column' => 'Price / Stock',
            'seller_products_created_column' => 'Created',
            'seller_products_actions_column' => 'Actions',
            'seller_products_no_image' => 'No Image',
            'seller_products_save' => 'Save',
            'seller_products_edit_details' => 'Edit Details',
            'seller_products_stop_selling' => 'Stop Selling',
            'seller_products_not_selling' => 'You are not selling any products yet. Use the form above to create your first product.',
            'seller_products_back_to_dashboard' => '← Back to Seller Dashboard',

            'seller_edit_title' => 'Edit Product',
            'seller_edit_intro' => 'Update the details for this product.',
            'seller_edit_base_price_label' => 'Base Price (visible to all sellers):',
            'seller_edit_base_stock_label' => 'Base Stock:',
            'seller_edit_seller_price_label' => 'Your Selling Price:',
            'seller_edit_seller_stock_label' => 'Your Stock:',
            'seller_edit_image_hint' => 'Leave empty to keep the current image.',
            'seller_edit_save_changes' => 'Save Changes',

            'seller_orders_title' => 'My Orders',
            'seller_orders_intro' => 'These are orders that include products you sold. You can update their status here.',
            'seller_orders_order_id' => 'Order ID',
            'seller_orders_customer' => 'Customer',
            'seller_orders_total_amount' => 'Total Amount',
            'seller_orders_status' => 'Status',
            'seller_orders_date' => 'Date',
            'seller_orders_no_orders' => 'You don’t have any orders yet.',
            'seller_orders_back_to_dashboard' => '← Back to Seller Dashboard',

            'order_details_title' => 'Order Details',
            'order_details_back' => '← Back to Dashboard',
            'order_info_title' => 'Order Information',
            'order_info_order_id' => 'Order ID:',
            'order_info_order_date' => 'Order Date:',
            'order_info_status' => 'Status:',
            'order_info_shipping_address' => 'Shipping Address:',
            'order_items_title' => 'Order Items',
            'order_items_product' => 'Product',
            'order_items_seller' => 'Seller',
            'order_items_price' => 'Price',
            'order_items_quantity' => 'Quantity',
            'order_items_subtotal' => 'Subtotal',
            'order_items_view_product' => 'View Product',
            'order_items_empty' => 'No items found for this order.',
            'order_summary_title' => 'Order Summary',
            'order_summary_subtotal' => 'Subtotal:',
            'order_summary_shipping' => 'Shipping:',
            'order_summary_shipping_free' => 'Free',
            'order_summary_total' => 'Total:',
            'order_customer_info_title' => 'Customer Information',
            'order_customer_name' => 'Name:',
            'order_customer_email' => 'Email:',
            'order_customer_phone' => 'Phone:',

            'profile_title' => 'My Profile',
            'profile_account_overview' => 'Account Overview',
            'profile_name_label' => 'Name:',
            'profile_username_label' => 'Username:',
            'profile_email_label' => 'Email:',
            'profile_phone_label' => 'Phone:',
            'profile_address_label' => 'Address:',
            'profile_role_label' => 'Role:',
            'profile_member_since_label' => 'Member since:',
            'profile_update_profile_title' => 'Update Profile',
            'profile_full_name_label' => 'Full Name:',
            'profile_update_profile_button' => 'Save Profile',
            'profile_change_password_title' => 'Change Password',
            'profile_current_password_label' => 'Current Password:',
            'profile_new_password_label' => 'New Password:',
            'profile_confirm_new_password_label' => 'Confirm New Password:',
            'profile_update_password_button' => 'Update Password',
            'profile_update_success' => 'Profile updated successfully.',
            'profile_update_required_error' => 'Full name, username, and email are required.',
            'profile_update_username_email_taken' => 'Username or email is already taken.',
            'profile_update_failed' => 'Failed to update profile. Please try again.',
            'profile_password_mismatch' => 'New passwords do not match.',
            'profile_current_password_incorrect' => 'Current password is incorrect.',
            'profile_password_update_success' => 'Password updated successfully.',
            'profile_password_update_failed' => 'Failed to update password. Please try again.',

            'cart_title' => 'Shopping Cart',
            'cart_table_product' => 'Product',
            'cart_table_seller' => 'Seller',
            'cart_table_price' => 'Price',
            'cart_table_quantity' => 'Quantity',
            'cart_table_total' => 'Total',
            'cart_table_action' => 'Action',
            'cart_remove_confirm' => 'Remove this item from cart?',
            'cart_remove_button' => 'Remove',
            'cart_total_label' => 'Total:',
            'cart_checkout_button' => 'Proceed to Checkout',
            'cart_empty_message' => 'Your cart is empty.',
            'cart_empty_continue' => 'Continue Shopping',
            'button_cancel' => 'Cancel',

            // Flash / status messages for products (seller & admin)
            'flash_product_created' => 'Product created successfully.',
            'flash_product_updated' => 'Product updated successfully.',
            'flash_product_added' => 'Product added successfully',
            'flash_product_deleted' => 'Product deleted successfully',
            'flash_product_stopped_selling' => 'You have stopped selling this product.',
            'flash_image_upload_failed' => 'Failed to upload image',
            'flash_invalid_file_type' => 'Invalid file type. Only JPG, JPEG, PNG, GIF, and WEBP are allowed.',
            'error_seller_product_not_found' => 'Product not found or not associated with your seller account.',

            // Confirmation dialogs
            'confirm_stop_selling_product' => 'Stop selling this product?',
            'confirm_delete_product' => 'Are you sure you want to delete this product?',

            'product_seller_section_title' => 'Seller Information',
            'product_seller_section_seller' => 'Seller:',
            'product_seller_section_price' => 'Price:',
            'product_seller_section_stock' => 'Stock:',
            'product_seller_section_rating' => 'Rating:',
            'product_seller_section_reviews' => 'Reviews:',
        ],
        'zh' => [
            'nav_admin' => '后台管理',
            'nav_seller' => '卖家中心',
            'nav_cart' => '购物车',
            'nav_dashboard' => '我的主页',
            'nav_profile' => '个人资料',
            'nav_logout' => '退出登录',
            'nav_login' => '登录',
            'nav_register' => '注册',
            'nav_cart_with_count' => '购物车 (%d)',
            'brand_name' => '商城',
            'theme_night' => '夜间',
            'theme_light' => '日间',

            'dashboard_title' => '我的主页',
            'dashboard_menu' => '菜单',
            'dashboard_my_orders' => '我的订单',
            'dashboard_profile_settings' => '个人资料与设置',
            'dashboard_continue_shopping' => '继续购物',
            'dashboard_cart' => '购物车',
            'dashboard_become_seller' => '成为卖家',

            'orders_table_order_id' => '订单编号',
            'orders_table_total' => '总金额',
            'orders_table_status' => '状态',
            'orders_table_date' => '日期',
            'orders_table_action' => '操作',
            'orders_view_details' => '查看详情',
            'orders_empty_message' => '你还没有订单。',
            'orders_start_shopping' => '开始购物',

            'order_status_pending' => '待处理',
            'order_status_processing' => '处理中',
            'order_status_shipped' => '已发货',
            'order_status_delivered' => '已送达',
            'order_status_cancelled' => '已取消',

            'language_select_title' => '选择语言',
            'language_select_intro' => '请选择你偏好的语言。',
            'language_english' => '英文',
            'language_chinese' => '中文',
            'language_save' => '保存语言',
            'profile_language_label' => '语言',

            'search_placeholder' => '搜索商品...',
            'search_button' => '搜索',

            'category_all' => '全部',
            'category_electronics' => '电子产品',
            'category_clothing' => '服饰',
            'category_home_kitchen' => '家居与厨房',
            'category_books' => '书籍',
            'category_sports' => '运动',

            'product_stock_label' => '库存',
            'home_view_details' => '查看详情',
            'home_login_to_buy' => '登录以购买',
            'product_description_title' => '描述',
            'product_available_from_sellers' => '可从以下卖家购买：',
            'product_quantity_label' => '数量：',
            'product_add_to_cart_button' => '添加到购物车',
            'product_out_of_stock' => '库存不足',
            'product_no_sellers_message' => '没有可用的卖家。',

            'seller_dashboard_title' => '卖家仪表板',
            'seller_dashboard_welcome' => '欢迎你，%s。以下是你的销售概览。',
            'seller_dashboard_total_products' => '商品总数',
            'seller_dashboard_total_orders' => '订单总数',
            'seller_dashboard_gross_revenue' => '总销售额',
            'seller_dashboard_platform_fees' => '平台手续费 (10%)',
            'seller_dashboard_net_revenue' => '净收入（扣除手续费后）',
            'seller_dashboard_actions' => '卖家操作',
            'seller_dashboard_my_products' => '我的商品',
            'seller_dashboard_my_orders' => '我的订单',
            'seller_dashboard_back_to_store' => '返回商店',

            'seller_products_title' => '我的商品',
            'seller_products_intro' => '创建并管理你出售的商品。',
            'seller_products_add_new' => '新增商品',
            'seller_products_name' => '名称',
            'seller_products_description' => '描述',
            'seller_products_price' => '价格',
            'seller_products_stock' => '库存',
            'seller_products_image' => '图片',
            'seller_products_create_button' => '创建商品',
            'seller_products_your_products' => '你的商品',
            'seller_products_image_column' => '图片',
            'seller_products_name_column' => '名称',
            'seller_products_price_stock_column' => '价格 / 库存',
            'seller_products_created_column' => '创建时间',
            'seller_products_actions_column' => '操作',
            'seller_products_no_image' => '暂无图片',
            'seller_products_save' => '保存',
            'seller_products_edit_details' => '编辑详情',
            'seller_products_stop_selling' => '停止销售',
            'seller_products_not_selling' => '你还没有出售任何商品。请使用上面的表单创建第一件商品。',
            'seller_products_back_to_dashboard' => '← 返回卖家仪表板',

            'seller_edit_title' => '编辑商品',
            'seller_edit_intro' => '更新此商品的详情。',
            'seller_edit_base_price_label' => '基础价格（对所有卖家可见）：',
            'seller_edit_base_stock_label' => '基础库存：',
            'seller_edit_seller_price_label' => '你的销售价格：',
            'seller_edit_seller_stock_label' => '你的库存：',
            'seller_edit_image_hint' => '留空以保持当前图片。',
            'seller_edit_save_changes' => '保存更改',

            'seller_orders_title' => '我的订单',
            'seller_orders_intro' => '这些订单包含你出售的商品。你可以在这里更新订单状态。',
            'seller_orders_order_id' => '订单编号',
            'seller_orders_customer' => '客户',
            'seller_orders_total_amount' => '总金额',
            'seller_orders_status' => '状态',
            'seller_orders_date' => '日期',
            'seller_orders_no_orders' => '你还没有任何订单。',
            'seller_orders_back_to_dashboard' => '← 返回卖家仪表板',

            'order_details_title' => '订单详情',
            'order_details_back' => '← 返回主页',
            'order_info_title' => '订单信息',
            'order_info_order_id' => '订单编号：',
            'order_info_order_date' => '下单时间：',
            'order_info_status' => '状态：',
            'order_info_shipping_address' => '收货地址：',
            'order_items_title' => '订单商品',
            'order_items_product' => '商品',
            'order_items_seller' => '卖家',
            'order_items_price' => '单价',
            'order_items_quantity' => '数量',
            'order_items_subtotal' => '小计',
            'order_items_view_product' => '查看商品',
            'order_items_empty' => '此订单没有商品。',
            'order_summary_title' => '订单汇总',
            'order_summary_subtotal' => '商品小计：',
            'order_summary_shipping' => '运费：',
            'order_summary_shipping_free' => '免费',
            'order_summary_total' => '合计：',
            'order_customer_info_title' => '客户信息',
            'order_customer_name' => '姓名：',
            'order_customer_email' => '邮箱：',
            'order_customer_phone' => '电话：',

            'profile_title' => '我的资料',
            'profile_account_overview' => '账户概览',
            'profile_name_label' => '姓名：',
            'profile_username_label' => '用户名：',
            'profile_email_label' => '邮箱：',
            'profile_phone_label' => '电话：',
            'profile_address_label' => '地址：',
            'profile_role_label' => '角色：',
            'profile_member_since_label' => '注册时间：',
            'profile_update_profile_title' => '更新资料',
            'profile_full_name_label' => '姓名：',
            'profile_update_profile_button' => '保存资料',
            'profile_change_password_title' => '修改密码',
            'profile_current_password_label' => '当前密码：',
            'profile_new_password_label' => '新密码：',
            'profile_confirm_new_password_label' => '确认新密码：',
            'profile_update_password_button' => '更新密码',
            'profile_update_success' => '资料更新成功。',
            'profile_update_required_error' => '姓名、用户名和邮箱为必填项。',
            'profile_update_username_email_taken' => '用户名或邮箱已被使用。',
            'profile_update_failed' => '更新资料失败，请重试。',
            'profile_password_mismatch' => '两次输入的新密码不一致。',
            'profile_current_password_incorrect' => '当前密码不正确。',
            'profile_password_update_success' => '密码更新成功。',
            'profile_password_update_failed' => '更新密码失败，请重试。',

            'cart_title' => '购物车',
            'cart_table_product' => '商品',
            'cart_table_seller' => '卖家',
            'cart_table_price' => '单价',
            'cart_table_quantity' => '数量',
            'cart_table_total' => '小计',
            'cart_table_action' => '操作',
            'cart_remove_confirm' => '从购物车中移除该商品？',
            'cart_remove_button' => '移除',
            'cart_total_label' => '合计：',
            'cart_checkout_button' => '去结算',
            'cart_empty_message' => '你的购物车是空的。',
            'cart_empty_continue' => '继续购物',
            'button_cancel' => '取消',

            // Flash / status messages for products (seller & admin)
            'flash_product_created' => '商品创建成功。',
            'flash_product_updated' => '商品更新成功。',
            'flash_product_added' => '商品添加成功。',
            'flash_product_deleted' => '商品删除成功。',
            'flash_product_stopped_selling' => '你已停止销售此商品。',
            'flash_image_upload_failed' => '图片上传失败。',
            'flash_invalid_file_type' => '文件类型无效。只允许 JPG、JPEG、PNG、GIF 和 WEBP。',
            'error_seller_product_not_found' => '未找到该商品，或该商品不属于你的卖家账号。',

            // Confirmation dialogs
            'confirm_stop_selling_product' => '停止销售此商品？',
            'confirm_delete_product' => '确定要删除此商品吗？',

            'product_seller_section_title' => '卖家信息',
            'product_seller_section_seller' => '卖家：',
            'product_seller_section_price' => '价格：',
            'product_seller_section_stock' => '库存：',
            'product_seller_section_rating' => '评分：',
            'product_seller_section_reviews' => '评论：',
        ],
    ];

    $lang = getCurrentLanguage();
    if (isset($translations[$lang][$key])) {
        return $translations[$lang][$key];
    }
    if (isset($translations['en'][$key])) {
        return $translations['en'][$key];
    }
    return $key;
}

function translateCategoryLabel(string $name): string {
    $slug = strtolower(trim(preg_replace('/[^a-z0-9]+/i', '_', $name), '_'));
    $key = 'category_' . $slug;
    $translated = t($key);
    if ($translated === $key) {
        return $name;
    }
    return $translated;
}
